index.html

Added HyperLinks

---

index.html

Resolved #13 . Added Stay connected with icons that are also links.

Stay Connected Added 

---

index.html

Reverting, does not include the hyperlinks

Revert "Stay Connected Added "

---

index.html

Merge the branch dedicated to Issue #10. Adds the section for FAQs to index.html and should change no other files.

Added FAQ section to index

---

index.html

Resolves Issue #13 . Adds/Fixes Stay Connected portion.

Stay Connected

---

index.html

Resolves Issue #11. But pricing table is currently not linked.

Adds Introduction Paragraph

---

index.html
style.css

Merge the navigation bar branch into main

Issue 6 navigation bar

---

.gitignore

git ignore to complete issue 8

---

index.html

Resolves issue #32 . adds link and sentence.

added link and sentence

---

index.html

Issue 37 fix connected

---

connection.php
index.php
login.php
welcome.php

added login feature with check of successful completion and made edits. Resolves #47 and resolves #51 .

added login and welcome made some edits to index and connection

---

welcome.php

SQL changes documented in the associated issue.

Added table to welcome.php

---

create.php
delete.php
login.php
welcome.php

Adds create and delete functionality to the CRUD table, as well as some other changes to welcome.php.
Also, I added session_start() to some files to get username info.

57 add create delete functionality

---

read.php
update.php
welcome.php

Adds update.php and read.php which allow for the update and read functionality for the ratings table in the database. Also made some changes to welcome.php to pass the id to these files.

60 update read functions for ratings table

---

index.php
register.php

Adds user registration funtionality. Resolves Issue #61.

added user registration

---

index.php
login.php
register.php
welcome.php

Bugs this branch fixes:
- incorrect user/pass message not showing up 
- being able to access welcome.php from register.php after a failed login
- Passsword hashing not seeming to work
PLEASE NOTE:
you also need to remove the salt column in the login table, and set the password column to 255 characters

Bug fix with welcome

---

htdocs/create.php
htdocs/delete.php
htdocs/index.php
htdocs/login.php
htdocs/logout.php
htdocs/read.php
htdocs/register.php
htdocs/update.php
htdocs/welcome.php

added api functionality to CRUD, register, login, resolves #82

added api functionality that was checked with postman

---

App.js

Successful fetch implementation.
Username is a placeholder for now, to be replaced with username variable once login is implemented

Fetch from rest api

---

NeuroTuneFrontend/app.json
NeuroTuneFrontend/app/_layout.jsx
NeuroTuneFrontend/app/create.jsx
NeuroTuneFrontend/app/delete.jsx
NeuroTuneFrontend/app/index.jsx
NeuroTuneFrontend/app/list.jsx
NeuroTuneFrontend/app/update.jsx
NeuroTuneFrontend/constants/api.js
NeuroTuneFrontend/package-lock.json
htdocs/Controller/Api/RatingController.php

In NeuroTuneFrontend/constants/api.js:
make sure to change your IP:
BASE_URL = "http://129.133.73.252/index.php";

CRUD implementation: UI + API fetch

---

README.md

Partially resolves issue #101 .

Add postman photos ro readme

---

NeuroTuneFrontend/app/(app)/_layout.jsx
NeuroTuneFrontend/app/(app)/delete.jsx
htdocs/Controller/Api/RatingController.php
htdocs/Model/RatingModel.php

This one's a little bit iffy still - give it time to load, maybe hit delete a second time if it didn't go through.
If others can, it would be great to get a style overhaul on the new stuff here, or maybe figure out a way to indicate if the request went through or not (seems to work fine when it does go through).
Also, you need to manually reload the page after creating a new rating, I couldn't figure out how to reload a tab after a change in another tab

111 add username functionality to delete

---

NeuroTuneFrontend/app/(app)/create.jsx
htdocs/Controller/Api/RatingController.php

Adds the login username to create, and the ability to alert proper error messages.

109 add username functionality to create

---

NeuroTuneFrontend/app/(app)/_layout.jsx
NeuroTuneFrontend/app/(app)/delete.jsx
NeuroTuneFrontend/app/(app)/logout.jsx

Test this one out well - I think I caught all the crashes but I'm not sure
(getting user.username must happen inside a function that is called via button, can't be running while logout is).

Logout fixed

---

NeuroTuneFrontend/app/(app)/update.jsx
htdocs/Controller/Api/RatingController.php

Adds username functionality to update, like the previous ones w/ delete and create

115 add username functionality to update

---

NeuroTuneFrontend/app/(app)/_layout.jsx
NeuroTuneFrontend/app/(app)/search.jsx

resolves issue #124 . adds search bar tab and search bar to app still needs a database to be connected to for functionality.

Issue 124 search bar

---

NeuroTuneFrontend/app/(app)/create.jsx
README.md
htdocs/Controller/Api/DataController.php
htdocs/Model/DataModel.php
htdocs/inc/bootstrap.php

Make sure to check the readme for the instructions for the new database
I'm gonna try adding stuff for suggested songs based off of this data - feel free to update the table with more columns for stuff later on

Create lyrics data

---

NeuroTuneFrontend/app/(app)/create.jsx
README.md
htdocs/Controller/Api/DataController.php

This one makes create really slow, so make sure to watch the debug logs to know it's working. The code is kind of a mess, sorry.
Also, make sure to update phpmyadmin with the new table. I would also recommend deleting all of the data currently in songdata, if you have any, since the intended code is to update both of these tables at once.

Create lyric similarity

---

NeuroTuneFrontend/app/(app)/list.jsx

was having a lot of trouble getting a backend to work for this, so thought I would just add in frontend rn. This is frontend for users to click on the emotion they feel from each song. Resolves issue #128 .

added frontend emotion piece 

---

NeuroTuneFrontend/app/(app)/_layout.jsx
NeuroTuneFrontend/app/(app)/logout.jsx
NeuroTuneFrontend/app/(auth)/register.jsx
htdocs/Controller/Api/DataController.php
htdocs/Controller/Api/RatingController.php
htdocs/Model/DataModel.php
htdocs/Model/RatingModel.php

Changes are made in the logout tab.
It's super ugly but it should be functional. I will add more options later.

Suggestion candidate

---

NeuroTuneFrontend/app/(app)/logout.jsx

improved UI for profile pag. Resolves issue #131 .

ui improvements to profile page

---

NeuroTuneFrontend/app/(app)/create.jsx

adds loading spinner when user clicks create before it alerts as successful. Resolves issue #133 .

Add loading to create

---

NeuroTuneFrontend/app/(app)/logout.jsx
htdocs/Controller/Api/RatingController.php
htdocs/Model/RatingModel.php

Profile page UI might need more updates after this, sorry.
Also, at some point we should consider making it so that song / artist names or combos that we can't find lyrics for shouldn't be considered as candidates, maybe.

Rating component

---

README.md
htdocs/Controller/Api/DataController.php
htdocs/Model/DataModel.php

Adds the emotion table instructions to readme and the appropriate functions to htdocs

Emotion table

---

NeuroTuneFrontend/app/(app)/logout.jsx

added toggling switches and cleaned up some things

profile ui update
